jwt:
  secret: ${SECRET_KEY}

admin:
  password: ${ADMIN_PASS}

spring:
  application:
    name: hospitalmanagement

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/hms_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

